# Generated by Django 2.0 on 2019-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20190330_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_wallet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
