# Generated by Django 2.0 on 2019-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190429_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
