# Generated by Django 2.1 on 2019-12-12 19:18

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190430_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_profile_id', models.IntegerField()),
                ('receiver_profile_id', models.IntegerField()),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('message', fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BarCodeTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_profile_id', models.IntegerField()),
                ('receiver_barcode', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('sender_emailid', fernet_fields.fields.EncryptedCharField(blank=True, max_length=35, null=True)),
                ('message', fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='barcode_val',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='newsport',
            name='news_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
