# Generated by Django 3.0.1 on 2020-01-23 19:45

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191212_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('first_name', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('last_name', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20, unique=True)),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=254)),
                ('address_line_1', fernet_fields.fields.EncryptedCharField(max_length=50)),
                ('address_line_2', fernet_fields.fields.EncryptedCharField(blank=True, max_length=50)),
                ('postal_code', fernet_fields.fields.EncryptedCharField(max_length=7)),
                ('city', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('country', fernet_fields.fields.EncryptedCharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('referral_contact', models.CharField(blank=True, max_length=15)),
                ('promo_coupon', models.CharField(blank=True, max_length=100)),
                ('ic', fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
