# Generated by Django 3.0.1 on 2020-01-23 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='username',
        ),
        migrations.AddField(
            model_name='form',
            name='barcode_val',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=50),
        ),
    ]
