# Generated by Django 2.0 on 2019-04-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityitem',
            old_name='twentyfiveekg_price',
            new_name='twentyfivekg_price',
        ),
    ]
