# Generated by Django 2.0 on 2019-04-04 20:23

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20190405_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityitem',
            name='brand',
            field=fernet_fields.fields.EncryptedCharField(max_length=50),
        ),
    ]
