# Generated by Django 2.0 on 2019-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_auto_20190405_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='grocery_wallet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
